In [289]:
import numpy as  np
import pandas as pd

In [290]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data", header=None)

In [291]:
from sklearn.model_selection import train_test_split


In [292]:
df.columns=['ID','clump_thick','unif_cell_size','unif_cell_shape','marg_adhesion','single_epi_cell_size','bare_nuclei','bland_chromatin','normal_nucleoli','mitoses','class']
df.replace('?',-99999, inplace=True)
df.drop(columns=['ID']).tail()

clump_thick  unif_cell_size  unif_cell_shape  marg_adhesion  \
694            3               1                1              1   
695            2               1                1              1   
696            5              10               10              3   
697            4               8                6              4   
698            4               8                8              5   

     single_epi_cell_size bare_nuclei  bland_chromatin  normal_nucleoli  \
694                     3           2                1                1   
695                     2           1                1                1   
696                     7           3                8               10   
697                     3           4               10                6   
698                     4           5               10                4   

     mitoses  class  
694        1      2  
695        1      2  
696        2      4  
697        1      4  
698        1      4

In [293]:
x=np.array(df.drop(['class','ID'],1)).astype(float)
x[0:5]

array([[ 5.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.],
       [ 5.,  4.,  4.,  5.,  7., 10.,  3.,  2.,  1.],
       [ 3.,  1.,  1.,  1.,  2.,  2.,  3.,  1.,  1.],
       [ 6.,  8.,  8.,  1.,  3.,  4.,  3.,  7.,  1.],
       [ 4.,  1.,  1.,  3.,  2.,  1.,  3.,  1.,  1.]])

In [294]:
y=np.array(df['class'])
y[0:5]

array([2, 2, 2, 2, 2], dtype=int64)

In [352]:
X_train,X_test,y_train,y_test = train_test_split(x,y, test_size=0.10)

In [353]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [354]:
from sklearn import neighbors
from sklearn import preprocessing

In [355]:
k=6
clf = neighbors.KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)


In [356]:
clf

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [357]:
yhat=clf.predict(X_test)
yhat

array([2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4,
       2, 2, 4, 2, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 4,
       2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2,
       2, 2, 2, 2], dtype=int64)

In [358]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, clf.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.9761526232114467
Test set Accuracy:  0.9714285714285714


In [359]:
unknown_cell=np.array([[3,1,1,1,2,2,3,1,1],[8,10,10,8,7,10,9,7,1],[1,1,1,1,5,1,3,1,1]])
unknown_cell=unknown.reshape(len(unknown),-1)

In [360]:
yhat=clf.predict(unknown_cell)
yhat

array([2, 4, 2], dtype=int64)